### ISSUE TITLE
Wrong behaviour if multiple macros in one template

### ISSUE THREAD

**Issue by vilinski** [joaroyen/ReSharperExtensions#8]
I have following template for unit test classes, where $ClassName$ and $TestName$ use the same macro "Ensures ... valid C# identifier". The problem is, the ClassName and TestName are edited simultaneously, so if it were just one place holder

```
[Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute]
public class $ClassName$
{
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute]
    public void $TestName$()
    {
        // ARRANGE
        $END$

        // ACT

        // ASSERT
        Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail("NotImplemented");
    }
}
```

**Comment by joaroyen** [comment]
Thanks for reporting this issue :)

I was able to fix this issue in my updated ReSharper.LiveTemplates extension for ReSharper 9.1: https://resharper-plugins.jetbrains.com/packages/JoarOyen.ReSharper.LiveTemplates/2.0.1

I don't have ReSharper 8 on any of my machines anymore and I am not able to port this fix and verify if it works in earlier version. If you would like to try to back port this fix yourself, you can look at this commit: https://github.com/joaroyen/ReSharper.LiveTemplates/commit/776864408fe1e305fd068aef208c5eff83c8eaf4

As a workaround for the ReShaprer 8, you would need to have two templates. One for the class and another one for the test method.
